### ISSUE TITLE
What to do with those 'negative' (non-hit) molecules after each iteration

### ISSUE THREAD

**Issue by linpei26** [jamesgleave/DD_protocol#10]
Hello!

We are very interested in the deep docking workflow.
Here I have a simple question:

After each iteration, there will be a large number of molecules that not labeled as hits.
One way to deal with these 'negative' molecules is to simply discard them. That means, such 'negative' molecules will be removed  from then on.
Alternatively, these 'negative' molecules, along with those 'positive' molecules that were virtual hits but not being sampled to do augmentation of training set, should be used for inference in the next iteration.
Could you please take a look and let me know your opinion? I feel that 'negative' molecules should go into the next iteration but I am not sure.

Thank you!
BEST,

Pei
.--. . ..

**Comment by fgentile89** [comment]
All the molecules in the library are re-evaluated in each iteration, so non-hit classified compounds are not discarded.
