### ISSUE TITLE
Inquiry Regarding Ligand Preparation in Stage IV of Deep Docking Project

### ISSUE THREAD

**Issue by STM32F103C8T6** [jamesgleave/DD_protocol#11]
Dear jamesgleave,

I hope this email finds you well. Firstly, I would like to express my sincere gratitude to the Deep Docking team for their remarkable contributions to the field of accelerating molecular docking through deep learning. Your work in this domain has been invaluable, and it is greatly appreciated.

I am writing to seek clarification on a specific aspect of the project, particularly in Stage IV: ligand preparation (DD phase 2). In this context, my inquiry revolves around the use of the OMEGA module for ligand preparation in Glide docking. Obtaining academic licenses for OpenEye's software can be challenging, and I am exploring alternative options.

Specifically, I would like to know if it is mandatory to utilize the OMEGA module for ligand preparation in Glide docking during Stage IV. Given the potential challenges associated with obtaining academic licenses for OpenEye, I am curious whether the ligprep module in Maestro can be a viable alternative for this purpose. Could you please provide some insights into the compatibility and capabilities of the ligprep module in addressing the ligand preparation requirements for Glide docking in Stage IV?

Your guidance on this matter would be immensely helpful, and I appreciate your time and assistance. Thank you once again for your groundbreaking work in advancing the field of molecular docking, and I look forward to your response.

Best regards,
Shang Xinci
Soochow University School of Pharmacy

**Comment by fgentile89** [comment]
Hi Shang, you can use whatever you want to prepare the molecules - ligprep is fine as well
