### ISSUE TITLE
[Feature Request] Docker Container

### ISSUE THREAD

**Issue by itsOwen** [jamesgleave/DD_protocol#4]
Hello James and the devs,

Is there a way you guys can make a working docker container for everyone to use with SLURM setup. It would help a lot of people.

Thanks

**Comment by fgentile89** [comment]
Definitely in our to-do list. Meanwhile, have a look into our GUI [https://github.com/jamesgleave/DeepDockingGUI](url) which should be straightforward to use on SLURM clusters, if you like to use Autodock-GPU for docking
