### ISSUE TITLE
conda requirements

### ISSUE THREAD

**Issue by ghost** [jamesgleave/DD_protocol#7]
Hi
Can you mention how to install the dependencies for DD protocol?
Also I have a 3 million small molecule library in sdf format, can I use it as a test for docking?
Thanks
Deb

**Comment by fgentile89** [comment]
[https://github.com/jamesgleave/DD_protocol/blob/main/utilities/environment.yml](url) should help with installing the dependencies. SDF files should be good for docking, depending on what program you are going to use. Best,

Francesco

**Comment by julmarci** [comment]
Hello Francesco. 

Keras dependency is missing in [https://github.com/jamesgleave/DD_protocol/blob/main/utilities/environment.yml](https://github.com/jamesgleave/DD_protocol/issues/url). The version that is automatically installed in conda, based on the rest of the requirements, has this problem when loading the models. 

"AttributeError: 'str' object has no attribute 'decode'"

https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi

What version of Keras should we install?

Thank you so much.

**Comment by fgentile89** [comment]
Hi, 
Have you tried to reinstall the h5py package as they suggested in that post? In our machines, we have keras 2.6.0 and h5py 3.1.0

**Comment by julmarci** [comment]
Installing a previous version of h5py solves the issue.

However, I wasn't able to install keras 2.6.0 together with tensorflow 1, so I'm wondering if this tool works with tensorflow 2 libraries.

**Comment by ghost** [comment]
hola, yo tengo el mismo problema con conda, podrías proporcionarnos un listado de las dependencias necesarias e instaladas en tu sistema con su respectiva versión, de ante mano te agradezco
